# Generated by Django 4.1.5 on 2023-04-08 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilesAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_1",
                    models.FileField(
                        default="default_file.pdf", upload_to="product_files/"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Files Admin",
                "verbose_name_plural": "Files Admin",
            },
        ),
    ]
