# Generated by Django 4.1.5 on 2023-04-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_filesadmin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filesadmin",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.product",
            ),
        ),
    ]
