# Generated by Django 4.1.5 on 2023-02-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment",
            field=models.TextField(default="null"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="website",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
