# Generated by Django 4.2 on 2023-04-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="filesadmin",
            name="title",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
