# Generated by Django 4.2 on 2023-04-09 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_filesadmin_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filesadmin",
            old_name="file_1",
            new_name="adminupload",
        ),
    ]
